title: "Jesse Freitag"
author: "Jesse"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:
  - {file: "index.html", title: "Home"}
  - {url: "https://jessefreitag.github.io/Jesse%20Freitag%20Resume.pdf", title: "Resume", target: "_blank"}
  - {file: "Projects.md", title: "Projects"}
  - {file: "contact_me.md", title: "Contact Me"}





external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, url: "mailto:jfreitag@uchicago.edu"}
  - {title: Github, url: "https://github.com/jessefreitag"}
  - {title: LinkedIn, url: "https://www.linkedin.com/in/jesse-freitag-bb77b5199/"}
  - {title: UChicago, url: "https://finmath.uchicago.edu/"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
